### ISSUE TITLE
Disable infinite (and centerMode) when totalItems < slidesToShow

### ISSUE THREAD

**Issue by abhinavdalal-iconnect** [YIZHUANG/react-multi-carousel#63]
**Describe the bug**
when the totalItems are less than slidesToShow in infinite mode; carosel goes blank

**To Reproduce**
1. clone https://github.com/abhinavdalal/matrimony-demo
2. git checkout 'demo_infinite_mode_error'
3. `npm i` and then `npm start`
4. login as shaadi/123
5. select 6 on dropdown (everything works as expected)
6. select 4 on dropdown -> ERROR (carousel goes blank after some flashes)

**Expected behavior**
disable the infinite (and centerMode) when totalItems < slidesToShow. IMO the concept of infinite should not apply if all items to be displayed are visible on the screen already. 

Note for totalItems = slidesToShow i think infinite mode stlii makes sense specialy with the centerMode as we would have an extra half and half on either side of the carousel ; but if ( totalItems < slidesToShow ) then just disable infinite mode makes sense IMO even with centerMode.

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [firefox]
 - Version [69]

**Smartphone (please complete the following information):**
same issues on small screens seen with devtools

**Comment by YIZHUANG** [comment]
Are you using the latest version? I believe this is fixed at some point.

**Comment by abhinavdalal-iconnect** [comment]
yes @YIZHUANG.. i am using react-multi-carousel@2.2.6

I am happy to help with a PR if you agree with the behavior of disabling infinite when (totalItems < slidesToShow ) :)

**Comment by YIZHUANG** [comment]
Yeah, please do. Thank you!

**Comment by YIZHUANG** [comment]
I just looked into, this bug was fixed at some points, but then later on some changes were introduced that broke it.  Should add test to this.  Basically you can reuse the function "notEnoughChildren" to disable it.

**Comment by YIZHUANG** [comment]
This is released in the latest version.

**Comment by jvence** [comment]
I'm using "react-multi-carousel": "^2.6.1" and this is still occuring.
